Repository AtlassianPS/JiraPS, pull requests merged in 2018-06, with the labels that each got.

#277 Improve error-handler to accommodate for ErrorDetails and non-JSON/HTML responses
  JiraPS/JiraPS.psm1
  JiraPS/Public/Invoke-JiraMethod.ps1
Labels: Status:In Review

#265 Implement removal of Jira issues via Remove-JiraIssue
  JiraPS/Public/Remove-JiraIssue.ps1
  Tests/Remove-JiraIssue.Tests.ps1
  docs/en-US/commands/Remove-JiraIssue.md
Labels: Area:Module, Issue:Enhancement, Status:In Review

#285 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Area:Repository, Issue:Enhancement, Status:In Review

#286 Fix Resolving of remote link object
  JiraPS.build.ps1
  JiraPS/Public/Get-JiraRemoteLink.ps1
  Tests/Get-JiraRemoteLink.Tests.ps1
  Tests/JiraPS.Integration.Tests.ps1
  appveyor.yml
Labels: Area:Module, Issue:Bug, Status:In Review

#288 Added `-Id` parameter to Remove-JiraFilter
  JiraPS/Public/Remove-JiraFilter.ps1
  Tests/Remove-JiraFilter.Tests.ps1
  docs/en-US/commands/Remove-JiraFilter.md
Labels: Area:Module, Issue:Enhancement, Status:In Review
