Repository AtlassianPS/JiraPS, pull requests merged in 2019-08, with the labels that each got.

#365 Find-JiraFilter
  JiraPS/Public/Find-JiraFilter.ps1
  Tests/Functions/Find-JiraFilter.Unit.Tests.ps1
  docs/en-US/commands/Find-JiraFilter.md
Labels: Area:Module, Issue:Enhancement, refactoring

#370 Changed ConfigServer to be in module's scope
  JiraPS/JiraPS.psm1
  JiraPS/Public/Get-JiraConfigServer.ps1
  JiraPS/Public/Set-JiraConfigServer.ps1
  Tests/Functions/Get-JiraConfigServer.Unit.Tests.ps1
  Tests/Functions/Set-JiraConfigServer.Unit.Tests.ps1
  Tests/JiraPS.Tests.ps1
  docs/en-US/commands/Get-JiraConfigServer.md
  docs/en-US/commands/Set-JiraConfigServer.md
Labels: Area:Module, Issue:Enhancement

#373 Added check for trailing `/` to be removed from `JiraServerUrl`
  JiraPS/Public/Get-JiraConfigServer.ps1
  Tests/JiraPS.Tests.ps1
Labels: Area:Module, Issue:Bug
