Repository AtlassianPS/JiraPS, pull requests merged in 2019-10, with the labels that each got.

#384 Fix email notification not sending
  JiraPS/Public/New-JiraUser.ps1
Labels: Area:Module, Issue:Bug

#385 Add support for activation/deactivation of accounts via Set-JiraUser
  JiraPS/Public/Set-JiraUser.ps1
  docs/en-US/commands/Set-JiraUser.md
Labels: Area:Module, Issue:Enhancement

#380 Speedup Invoke-WebRequests by disabling progress indicator.
  JiraPS/Public/Invoke-JiraMethod.ps1
Labels: Area:Module, enhancement
